CREATE TABLE request_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  request_id TEXT NOT NULL,
  api_key_id INTEGER NULL,
  route_id INTEGER NULL,
  route_name TEXT,
  provider_id INTEGER NULL,
  provider_name TEXT,
  target_id INTEGER NULL,
  public_model_name TEXT,
  upstream_model_name TEXT,
  client_ip TEXT,
  method TEXT,
  path TEXT,
  stream BOOLEAN NOT NULL DEFAULT FALSE,
  status_code INTEGER,
  upstream_status_code INTEGER,
  latency_ms INTEGER,
  time_to_first_chunk_ms INTEGER NULL,
  stream_completed BOOLEAN NULL,
  prompt_tokens INTEGER NULL,
  completion_tokens INTEGER NULL,
  total_tokens INTEGER NULL,
  error_code TEXT NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT (datetime('now'))
);
